version: "3.1"

services:
  db:
    image: postgis/postgis:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: m
      POSTGRES_PASSWORD: m
      POSTGRES_DB: m